-- 1번 정답
SELECT STUDENT_NO "학번", 
STUDENT_NAME "이름", 
TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY "입학년도";

-- 2번 정답
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번 정답
SELECT PROFESSOR_NAME,
CASE
WHEN TO_CHAR(SYSDATE, 'MMDD') > SUBSTR(PROFESSOR_SSN, 3,4)
THEN (TO_CHAR(SYSDATE, 'YY')+2000 -((SUBSTR(PROFESSOR_SSN, 1,2))+1900))+1

WHEN TO_CHAR(SYSDATE, 'MMDD') < SUBSTR(PROFESSOR_SSN, 3,4)
THEN TO_CHAR(SYSDATE, 'YY')+2000 -((SUBSTR(PROFESSOR_SSN, 1,2))+1900)
END "나이"

FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1;

-- 4번 정답
SELECT SUBSTR(PROFESSOR_NAME, 2, 2)
FROM TB_PROFESSOR;

-- 5번 정답
SELECT 
STUDENT_NO,
STUDENT_NAME
FROM TB_STUDENT
WHERE (EXTRACT (YEAR FROM TO_DATE(ENTRANCE_DATE, 'YYYY'))
- EXTRACT (YEAR FROM TO_DATE(STUDENT_SSN, 'YYYY'))) > 20;

-- 6번 정답
SELECT TO_CHAR(TO_DATE(20201225, 'YYYYMMDD'), 'DAY') FROM DUAL;

-- 7번 정답
SELECT TO_DATE('99/10/11', 'YYYY/MM/DD') 값1, 
      TO_DATE('49/10/11', 'YYYY/MM/DD') 값2,
      TO_DATE('99/10/11', 'RR/MM/DD')-100 값3, 
      TO_DATE('49/10/11', 'RR/MM/DD') 값4
FROM DUAL;

-- 8번 정답
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) > 2000;

-- 9번 정답
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10번 정답
SELECT DEPARTMENT_NO 학과번호, COUNT(*) 학생수
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;

-- 11번 정답
SELECT COUNT(*)
FROM TB_STUDENDT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12번 정답
SELECT EXTRACT(YEAR FROM TERM_NO) 년도, ROUND(POINT, 1) 년도별 평점
FROM TM_GRADE
GROUP BY EXTRACT(YEAR FROM TERM_NO)
HAVING TERM_NO BETWEEN '2001' AND '2004';

-- 13번 정답
SELECT DEPARTMENT_NO "학과 코드", COUNT(ABSENCE_YN) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
HAVING ABSENCE_YN = 'Y';

-- 14번 정답
SELECT STUDENT NAME 동일이름, COUNT(*) 동명인 수
FROM TB_STUDENT
WHERE COUNT(DISTINCT (STUDENT_NO)) > 1;

-- 15번 정답
SELECT SUBSTR(TERM_NO, 1, 4) 년도, 
       SUBSTR(TERM_NO, -1, 2) 학기, 
       CASE 
       WHEN SUBSTR(TERM_NO, -1, 2) = '01' THEN POINT
       WHEN 
      ELSE AVG(POINT) 평균
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO, 1, 4);
