-- 1번 정답
SELECT STUDENT_NO "학번", 
STUDENT_NAME "이름", 
TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY "입학년도";

-- 2번 정답
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번 정답
SELECT PROFESSOR_NAME,
CASE
WHEN TO_CHAR(SYSDATE, 'MMDD') > SUBSTR(PROFESSOR_SSN, 3,4)
THEN (TO_CHAR(SYSDATE, 'YY')+2000 -((SUBSTR(PROFESSOR_SSN, 1,2))+1900))+1

WHEN TO_CHAR(SYSDATE, 'MMDD') < SUBSTR(PROFESSOR_SSN, 3,4)
THEN TO_CHAR(SYSDATE, 'YY')+2000 -((SUBSTR(PROFESSOR_SSN, 1,2))+1900)
END "나이"

FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1;

-- 4번 정답
SELECT SUBSTR(PROFESSOR_NAME, 2, 2)
FROM TB_PROFESSOR;

-- 5번 정답
SELECT 
STUDENT_NO,
STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT (YEAR FROM TO_DATE(ENTRANCE_DATE, 'YYYY'))
- EXTRACT (YEAR FROM TO_DATE(STUDENT_SSN, 'YYYY'));



