 -- 01번
 SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, 순위
 FROM (
 SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
 FROM EMPLOYEE E
 JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
 JOIN DEPARTMENT D ON (D.DEPT_TITLE = E.DEPT_CODE)
 )
 WHERE ;

SELECT ROWNUM, EMP_NAME, SALARY
FROM (SELECT ROWNUM, EMP_NAME, SALARY
        FROM EMPLOYEE
        ORDER BY SALARY DESC)
WHERE ROWNUM <= 5;




 -- 02번
 SELECT DEPT_TITLE, SALARY
 FROM EMPLOYEE
 WHERE (DEPT_TITLE, SALARY) 
 IN (SELECT DEPT_TITLE, SUM(SALARY)
  FROM EMPLOYEE
  GROUP BY DEPT_TITLE);
--  AND SUM(SALARY) > SUM(SALARY) * 0.2;
 
 

    
 -- 03번
 
 