 -- 01번
SELECT RANK, EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
FROM (
SELECT RANK() OVER(ORDER BY (SALARY+(SALARY*NVL(BONUS,0)))*12 DESC)"RANK",
EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE))
WHERE ROWNUM <= 5;


 -- 02번
  SELECT DEPT_TITLE, SUM(SALARY)
  FROM EMPLOYEE E
  JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
  GROUP BY DEPT_TITLE
  HAVING SUM(SALARY) > 
   (SELECT SUM(SALARY) * 0.2
    FROM EMPLOYEE);

    
 -- 03번
    WITH MS AS 
    (
     SELECT SUM(SALARY) "총급여", AVG(NVL(SALARY, 0)) "평균급여"
     FROM EMPLOYEE 
     )
     SELECT 총급여, 평균급여
     FROM MS;
 
 