 -- 01번
 SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, 순위
 FROM (
 SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
 FROM EMPLOYEE E
 JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
 JOIN DEPARTMENT D ON (D.DEPT_TITLE = E.DEPT_CODE)
 WHERE BONUS IS NOT NULL AND SALARY *12
 )
 WHERE ROWNUM <= 5;

SELECT ROWNUM, EMP_NAME, SALARY
FROM (SELECT ROWNUM, EMP_NAME, SALARY
        FROM EMPLOYEE
        ORDER BY SALARY DESC)
WHERE ROWNUM <= 5;




 -- 02번
  SELECT DEPT_TITLE, SUM(SALARY)
  FROM EMPLOYEE E
  JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
  GROUP BY DEPT_TITLE
  HAVING SUM(SALARY) > 
   (SELECT SUM(SALARY) * 0.2
    FROM EMPLOYEE);

    
 -- 03번
    WITH TOPN_SAL AS 
    (
     SELECT SUM(SALARY) "총급여", AVG(NVL(SALARY, 0)) "평균급여"
     FROM EMPLOYEE 
     )
     SELECT 총급여, 평균급여
     FROM TOPN_SAL;
 
 