-- 01번 
CREATE TABLE TB_CATEGORY(
NAME VARCHAR2(10),
USE_YN CHAR(1) DEFAULT 'Y'
);


-- 02번
CREATE TABLE TB_CLASS_TYPE(
NO VARCHAR2(5) PRIMARY KEY,
NAME VARCHAR2(10)
-- CONSTRAINT TB_CLASS_TYPE_NO_PK PRIMARY KEY(NO)
);