-- 1번 정답
SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 학생이름;

-- 2번 정답
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3번 정답
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '99%'
AND (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%')
ORDER BY 학생이름;

-- 4번 정답
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR P
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;

-- 5번 정답
SELECT S.STUDENT_NO, TO_CHAR(POINT, 'FM99.00') "POINT"
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE CLASS_NO = 'C3118100' AND G.TERM_NO = '200402'
ORDER BY "POINT" DESC;

-- 6번 정답
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

-- 7번 정답
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

-- 8번 정답
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_PROFESSOR P ON (C.DEPARTMENT_NO = P.DEPARTMENT_NO)
ORDER BY 2;

-- 9번 정답
SELECT S.STUDENT_NO "학번", S.STUDENT_NAME "학생 이름", ROUND(AVG(NVL(POINT, 0)),1)"전체 평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NO , S.STUDENT_NAME
ORDER BY "학번";

-- 10번 정답
SELECT D.DEPARTMENT_NAME 학과이름 , S.STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.STUDENT_NO = 'A313047';

-- 11번 정답
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_CLASS C ON (C.CLASS_NO = G.CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND TERM_NO LIKE '2007%'
ORDER BY TERM_NO;

-- 12번 정답
SELECT C.CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR T ON (C.CLASS_NO = T.CLASS_NO)
WHERE D.CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;


-- 13번 정답
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정')
FROM TB_STUDENT S 
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과';

-- 14번 정답
SELECT STUDENT_NO, STUDENT_NAME, CLASS_NAME, TO_CHAR(ROUND(AVG(NVL(POINT)),1), 'FM99,99')
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_CLASS C ON (C.CLASS_NO = G.CLASS_NO)
WHERE ROUND(AVG(NVL(POINT)),1) >= 4.0;

-- 15번 정답
SELECT C.CLASS_NO, C.CLASS_NAME, ROUND(AVG(NVL(POINT,0)),1) 평점
FROM TB_CLASS C
JOIN TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
GROUP BY C.CLASS_NO, C.CLASS_NAME;


-- 16번 정답
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO IN
(SELECT DEPARTMENT_NO
FROM TB_STUDENT 
WHERE STUDENT_NAME = '최경희');

-- 17번 정답
-- 국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번
SELECT ROWNUM, STUDENT_NAME, STUDENT_NO
FROM (
SELECT S.STUDENT_NAME, S.STUDENT_NO, AVG(NVL(G.POINT,0))
FROM TB_STUDENT S
JOIN TB_GRADE G ON (G.STUDENT_NO = S.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NAME, S.STUDENT_NO
ORDER BY AVG(NVL(G.POINT,0)) DESC
)
WHERE ROWNUM <=1;

-- 18번 정답
SELECT DEPARTMENT_NAME, ROUND(AVG(NVL(POINT,0)),1)
FROM TB_CLASS C
JOIN TB_GRADE G ON (G.CLASS_NO = C.CLASS_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE CATEGORY IN (
SELECT CATEGORY
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME;
